### ISSUE TITLE
Article api doesn't contain excerpt

### ISSUE THREAD

**Issue by reggi** [reggi/shopify#9]
You can see there's no `excerpt` in the admin by adding `.json` to the end of a article's url.

```
https://{{SHOP_NAME}}.myshopify.com/admin/blogs/{{BLOG_ID}/articles/{{ARTICLE_ID}}.json
```

**Comment by reggi** [comment]
@carolineschnapp is this `article` `excerpt` a `metafield`? Is there any way to access it through the API?

**Comment by carolineschnapp** [comment]
I don't know @reggi Please post this question here: https://ecommerce.shopify.com/c/shopify-apis-and-technology

**Comment by reggi** [comment]
Great thanks! 

Putting this here for safe keeping: https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/article-api-doesn-t-contain-excerpt-243288
